# Generated by Django 4.1.1 on 2022-10-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_category_category_name_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transactionstock',
            name='price_total',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
